export enum InternshipStatus {
  WAITING_IN_DEPARTMENT_HEAD = 'WAITING_IN_DEPARTMENT_HEAD',
  WAITING_IN_DEAN = 'WAITING_IN_DEAN',
  WAITING_FOR_INSURANCE_ENTRY = 'WAITING_FOR_INSURANCE_ENTRY',
  INSURANCE_UPLOADED = 'INSURANCE_UPLOADED',
  COMPLETED = 'COMPLETED',

  REJECT_FROM_DEPARTMENT = 'REJECT_FROM_DEPARTMENT',
  REJECT_FROM_DEAN = 'REJECT_FROM_DEAN',
}
