export enum InternshipStatus {
  WAITING_IN_DEPARTMENT_HEAD = 'WAITING_IN_DEPARTMENT_HEAD',
  APPROVED_BY_DEPARTMENT = 'APPROVED_BY_DEPARTMENT',
  WAITING_IN_DEAN = 'WAITING_IN_DEAN',
  APPROVED_BY_DEAN = 'APPROVED_BY_DEAN',
  WAITING_IN_INTERNSHIP_COORDINATOR = 'WAITING_IN_INTERNSHIP_COORDINATOR',
  APPROVED_INTERNSHIP_COORDINATOR = 'APPROVED_INTERNSHIP_COORDINATOR',
  INSURANCE_ENTRY_DONE = 'INSURANCE_ENTRY_DONE ',
  REJECT = 'REJECT',
}
