export enum InternshipStatus {
  WAITING_IN_DEPARTMENT_HEAD = 'WAITING_IN_DEPARTMENT_HEAD',
  WAITING_IN_DEAN = 'WAITING_IN_DEAN',
  ACCEPTED = 'ACCEPTED',
  INSURANCE_ENTRY_DONE = 'INSURANCE_ENTRY_DONE ',
  REJECT = 'REJECT',
}
